packages:
  ProSourceManager:
    url: https://github.com/ProStore-iOS/ProSourceManager.git
    branch: main

targets:
  prostore:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [Sources/prostore]
    bundleId: com.prostoreios.prostore
    settings:
      IPHONEOS_DEPLOYMENT_TARGET: "15.0"
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
    info:
      path: "Info.plist"
      properties:
        CFBundleDisplayName: "ProStore"
        CFBundleName: "prostore"
        CFBundleVersion: "3"
        CFBundleShortVersionString: "1.0.2"
        UILaunchStoryboardName: "LaunchScreen"
        NSPrincipalClass: "UIApplication"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    dependencies:
      - package: ProSourceManager
        product: ProSourceManager