name: prostore

options:
  bundleIdPrefix: com.prostoreios

configs:
  Release: release
  Debug: debug

packages:
  ZsignPackage:
    url: https://github.com/khcrysalis/Zsign-Package.git
    branch: package
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    branch: main

targets:
  prostore:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [Sources/prostore]
    bundleId: com.prostoreios.prostore
    settings:
      IPHONEOS_DEPLOYMENT_TARGET: "16.0"
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
    info:
      path: "Info.plist"
      properties:
        CFBundleDisplayName: "ProStore"
        CFBundleName: "prostore"
        CFBundleVersion: "20"
        CFBundleShortVersionString: "1.3.1"
        UILaunchStoryboardName: "LaunchScreen"
        NSPrincipalClass: "UIApplication"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: true
        CFBundleURLTypes:
          - CFBundleURLName: "com.prostoreios.prostore"
            CFBundleURLSchemes:
              - prostore
              - ProStore
    dependencies:
      - package: ZsignPackage
        product: ZsignSwift
      - package: ZIPFoundation
        product: ZIPFoundation

schemes:
  ProStore-Release:
    build:
      targets:
        prostore: all
    run:
      config: Release
    archive:
      config: Release
