name: prostore

options:
  bundleIdPrefix: com.prostoreios

configs:
  Debug: debug
  Release: release

packages:
  ZsignPackage:
    url: https://github.com/khcrysalis/Zsign-Package.git
    branch: package

  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    branch: main

targets:
  prostore:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [Sources/prostore]
    bundleId: com.prostoreios.prostore
    settings:
      IPHONEOS_DEPLOYMENT_TARGET: "15.0"
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
    info:
      path: "Info.plist"
      properties:
        CFBundleDisplayName: "ProStore"
        CFBundleName: "prostore"
        CFBundleVersion: "9"
        CFBundleShortVersionString: "1.1.3"
        UILaunchStoryboardName: "LaunchScreen"
        NSPrincipalClass: "UIApplication"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: true
    dependencies:
      - package: ZsignPackage
        product: ZsignSwift
      - package: ZIPFoundation
        product: ZIPFoundation