name: prostore

options:
  bundleIdPrefix: com.prostoreios

configs:
  Debug: debug
  Release: release

targets:
  prostore:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [Sources/prostore]
    bundleId: com.prostoreios.prostore
    settings:
      IPHONEOS_DEPLOYMENT_TARGET: "15.0"
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
    info:
      path: "Info.plist"
      properties:
        CFBundleDisplayName: "ProStore"
        CFBundleName: "prostore"
        CFBundleVersion: "2"
        CFBundleShortVersionString: "1.0.1"
        UILaunchStoryboardName: "LaunchScreen"
        NSPrincipalClass: "UIApplication"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true