name: Deploy Github Pages Site

on:
  # Run manually
  workflow_dispatch:

  # Run on push if website changed OR the root JSON changed
  push:
    branches: ["main"]
    paths:
      - 'website/**'
      - 'app-repo.json'   # <- include the root file so changes to it trigger a build

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # COPY the single root file into the website/ source so Jekyll will include it
      - name: Copy root JSON into website (if present)
        run: |
          if [ -f ./app-repo.json ]; then
            echo "Found app-repo.json — copying into website/"
            mkdir -p website
            cp ./app-repo.json website/app-repo.json
          else
            echo "No app-repo.json in repo root — skipping copy"
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./website
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
